controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - eye_left_joint
      - arm_servo_gear_left_joint
      - arm_servo_gear_right_joint
      - leg_left_thigh_joint
      - leg_right_thigh_joint
      - leg_left_twist_joint
      - leg_right_twist_joint
      - leg_left_shin_joint
      - leg_right_shin_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
